package net.wrappy.im.helper;

/**
 * Created by hp on 1/17/2018.
 */

public enum ErrorCode {
    NO_NETWORK(0),
    WRONG_USERNAME_OR_PASSWORD(400),
    WP_VERSION_MISMATCH(8000),
    WP_ACCESS_IS_DENIED(8001),
    WP_INTERNAL_SERVER_ERROR(8002),
    WP_K_MEMBER_ALREADY_EXISTS(8003),
    WP_K_MEMBER_NOT_EXISTS(8004),
    WP_K_MEMBER_ALREADY_ACTIVATED(8005),
    WP_K_MEMBER_NOT_ACTIVATED(8006),
    WP_K_MEMBER_INVALID_EMAIL_ADDRESS(8007),
    WP_T_VERIFICATION_CODE_EXPIRY_OR_INVALID(8009),
    WP_K_ASSET_NOT_EXISTS(8010),
    WP_K_ASSET_RETAIN_FAILURE_FILE_EMPTY(8011),
    //    WP_K_ASSET_RETAIN_FAILURE_TTL_EXPIRED(8012),
    WP_K_ASSET_FETCH_FAILURE_FILE_UNAVAILABLE(8013),
    //    WP_K_ASSET_FETCH_FAILURE_TTL_EXPIRED(8014),
//    WP_K_ASSET_FETCH_FAILURE_FILE_UNOBTAINABLE(8015),
    WP_K_ASSET_TYPE_NOT_DETERMINES(8016),
    WP_K_REGISTRANT_NOT_EXISTS(8017),
    //    WP_K_BILLING_NOT_EXISTS(8018),
//    WP_K_BILLING_NOT_PAYABLE(8019),
    WP_T_MAIL_EXCEPTION(8020),
    WP_T_SMS_EXCEPTION_PAYLOAD_LENGTH_EXCEED_LIMIT(8021),
    WP_K_MEMBER_USERNAME_ALREADY_EXISTS(8022),
    WP_K_MEMBER_MOBILE_ALREADY_EXISTS(8023),
    WP_K_MEMBER_EMAIL_ALREADY_EXISTS(8024),
    WP_K_RESOURCE_NOT_EXISTS(8025),
    WP_K_MEMBER_SECURITY_QUESTIONS_NOT_FOUND(8026),
    WP_K_MEMBER_NOT_FOUND(8027),
    WP_K_MEMBER_EMAIL_NOT_FOUND(8028),
    WP_L_REPORT_ALREADY_EXISTS(8029),
    WP_L_REPORT_ALREADY_NOT_EXISTS(8030),
    WP_K_INVITER_MOBILE_NOT_EXISTS(8031),
    WP_K_CREATE_USER_ON_THE_XMPP_FAIL(8032);

    private int mErrorCode;

    ErrorCode(int errorCode) {
        mErrorCode = errorCode;
    }

    public int getErrorCode() {
        return mErrorCode;
    }

}
